# Generated by Django 5.2.4 on 2025-07-18 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo da despesa fixa (ex: Aluguel, Energia, etc.)', max_length=255, verbose_name='Nome da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor mensal da despesa fixa em reais', max_digits=10, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da despesa (opcional)', null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a despesa está ativa e deve ser considerada nos cálculos', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário da despesa fixa', on_delete=django.db.models.deletion.CASCADE, related_name='despesas_fixas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
