# Generated by Django 5.2.4 on 2025-07-18 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo da despesa variável (ex: Embalagem, Combustível, etc.)', max_length=255, verbose_name='Nome da Despesa')),
                ('valor_por_unidade', models.DecimalField(decimal_places=2, help_text='Valor unitário da despesa variável', max_digits=10, verbose_name='Valor por Unidade')),
                ('unidade_medida', models.CharField(help_text='Unidade de medida da despesa (ex: peça, kg, litro, etc.)', max_length=50, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da despesa variável', null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Define se a despesa variável está ativa para uso', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário da despesa variável', on_delete=django.db.models.deletion.CASCADE, related_name='despesas_variaveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Despesa Variável',
                'verbose_name_plural': 'Despesas Variáveis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'ativa'], name='despesavari_usuario_34bc5e_idx'), models.Index(fields=['nome'], name='despesavari_nome_9ce804_idx'), models.Index(fields=['created_at'], name='despesavari_created_c002b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nome'), name='unique_despesa_variavel_por_usuario')],
            },
        ),
    ]
