# Generated by Django 5.2.4 on 2025-07-18 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do ingrediente (ex: Farinha de Trigo, Açúcar, etc.)', max_length=255, verbose_name='Nome do Ingrediente')),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, help_text='Preço unitário do ingrediente em reais', max_digits=10, verbose_name='Preço por Unidade')),
                ('unidade_medida', models.CharField(help_text='Unidade de medida do ingrediente (ex: kg, litro, unidade, etc.)', max_length=50, verbose_name='Unidade de Medida')),
                ('fornecedor', models.CharField(blank=True, help_text='Nome do fornecedor ou local de compra (opcional)', max_length=255, null=True, verbose_name='Fornecedor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário do ingrediente', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
