# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_ingredientes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total dos ingredientes utilizados', max_digits=10, verbose_name='Custo dos Ingredientes')),
                ('custo_despesas_fixas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total das despesas fixas aplicáveis', max_digits=10, verbose_name='Custo das Despesas Fixas')),
                ('custo_despesas_variaveis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total das despesas variáveis aplicáveis', max_digits=10, verbose_name='Custo das Despesas Variáveis')),
                ('custo_total_producao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todos os custos de produção', max_digits=10, verbose_name='Custo Total de Produção')),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Preço sugerido baseado na margem de lucro desejada', max_digits=10, verbose_name='Preço de Venda Sugerido')),
                ('faturamento_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Faturamento esperado no período de análise', max_digits=12, verbose_name='Faturamento Previsto')),
                ('lucro_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lucro esperado no período de análise', max_digits=12, verbose_name='Lucro Previsto')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação da análise', verbose_name='Data de Criação')),
                ('produto', models.ForeignKey(help_text='Produto analisado', on_delete=django.db.models.deletion.CASCADE, related_name='analises_financeiras', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Análise Financeira',
                'verbose_name_plural': 'Análises Financeiras',
                'ordering': ['-created_at'],
            },
        ),
    ]
